---
#info: Start a Windows application on Desktop, user must be logged in
- name: "Start Desktop application '{{ winrun_path | basename }}'"
  script: 'winrun.sh {{ winrun_user }} {{ ansible_password }} {{ winrun_path }} "{{ winrun_args }}"'
  register: servermonkey_winrun_shell
  changed_when: servermonkey_winrun_shell.stdout != ""
  become: true

- debug:
    msg: |
      RC : {{ servermonkey_winrun_shell.rc }}
      OUT: {{ servermonkey_winrun_shell.stdout }}
      ERR: {{ servermonkey_winrun_shell.stderr }}
  when: servermonkey_debug

- name: Fail on errors
  fail:
    msg: "Script failed"
  when: '"winrun script failed" in servermonkey_winrun_shell.stderr'