---
#info: Start a Windows application on Desktop, user must be logged in
- name: "Start Desktop application '{{ winrun_path | basename }}'"
  script: 'winrun.sh "{{ winrun_user }}" "{{ ansible_password }}" "{{ winrun_path }}" "{{ winrun_args }}" "{{ winrun_force }}"'
  register: servermonkey_winrun_shell
  changed_when: servermonkey_winrun_shell.stdout != ""
  become: true

- debug:
    var: servermonkey_winrun_shell.stderr
  when:
    - servermonkey_winrun_shell.stderr is defined
    - servermonkey_winrun_shell.stderr != ""
    - not "Shared connection to" in servermonkey_winrun_shell.stderr
    - not "closed" in servermonkey_winrun_shell.stderr

- fail:
    msg: "Ansible-winrun failed for some other reason"
  when: '"Ansible-winrun OK" not in servermonkey_winrun_shell.stdout'

- include_role: name=servermonkey.ww_logger
  vars:
    ww_msg: "{{ servermonkey_winrun_shell.stdout }}"
    ww_logfile: servermonkey_winrun
    ww_nolog: true
    ww_archive: true
  when: 'servermonkey_winrun_shell.stdout is defined'